# runs compilation, testing, and clippy checking as a part of the CI
name: build
on: 
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: cargo test
        run: cargo test
      - name: cargo fmt
        run: cargo fmt -- --check
      - name: clippy lint
        run: cargo clippy -- -D warnings